### ISSUE TITLE
Per-queue `sidekiq_processed_jobs_total` metric

### ISSUE THREAD

**Issue by roobre** [Strech/sidekiq-prometheus-exporter#62]
👋🏻 

In my experience using this project to monitor sidekiq, `sidekiq_processed_jobs_total` is a very useful metric because it's a counter. This means that it easy to get meaningful rates at which jobs are being churned, but unfortunately it does not provide a `queue` label.

`sidekiq_queue_enqueued_jobs` does provide a `queue` label, but it's a gauge rather than a counter, which means it provides only a "snapshot" in time, and it's not very useful to know which queues have more activity, for example.

Would it be possible to have a `queue` label in `sidekiq_processed_jobs_total`, or is this not an infromation that sidekiq provides?

Thanks!

**Comment by Strech** [comment]
Hi @roobre and thanks for the issue.

> Would it be possible to have a queue label in sidekiq_processed_jobs_total, or is this not an infromation that sidekiq provides?

I don't have an exact answer from the top of my head, but it's possible to figure out by looking at the Sidekiq source code because most of the metrics comes either from pre-computed values (like the gauge you've mentioned) or we are able to compute them on our own.

If you could help me and take a look into that we can find a way to introduce something you need as an existing metric or a new one if it's possible.

**Comment by Strech** [comment]
I've checked the Sidekiq codebase and unfortunately, it doesn't accumulate per queue stats, even tho everything is ready for that.

To achieve that we would need to introduce the code, that must be plugged in as middleware or similar into each Sidekiq deployment to start count per queue metric. But this goes beyond the scope of easy-to-use gem.

Sorry, but I'm going to close this issue until there is a good solution.
